# https://github.com/marketplace/actions/enforce-pr-labels

name: Enforce PR Labels

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]

jobs:
  enforce-labels:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest

    steps:
      - uses: yogevbd/enforce-label-action@2.1.0
        with:
          REQUIRED_LABELS_ANY: "BLOCKED,chore,ci,docs,feat,fix,perf,refactor,release-major,release-minor,release-patch,release-prerelease,style,test"
          BANNED_LABELS: "BLOCKED"
